name: backend 测试

on:
  push:
    branches-ignore:
      - test-ci
    tags-ignore:
      - v*

jobs:
  test:
    env:
      CI: true
      KARMA_SINGLE_MODE: on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: install xvfb
      run: sudo apt-get install xvfb
    - name: yarn install, and test
      run: |
        cd ./backend
        yarn --version
        yarn cache clean
        yarn install
        yarn run test
